name: ePvP
author: EvertonPvP
main: me.everton.pvp.Main
version: 1.0
description: Plugin feito para a WoCNetwork por EvertonPvP
depend: [WorldGuard,WorldEdit,BarAPI,ProtocolLib,LibsDisguises]
commands:
  admin:
  cc:
  pc:
  sc:
  s:
  ac:
  hack:
  troll:
  rank:
  resetkdr:
  gm:
  build:
  clearlag:
  tag:
  spawnprotection:
  tag:
  resetkit:
  ping:
  spawn:
  setlocation:
  warp:
  warps:
  tp:
  tpall:
  1v1:
  spawnvillager:
  bau:
  criarinv:
  abririnv:
  doar:
  savestats: