name: ePvP
author: EvertonPvP
main: me.everton.epvp.Main
version: 1.0
description: Plugin de KitPvP criado por EvertonPvP
depend: [WorldGuard,WorldEdit,iTag,BarAPI]
commands: 
  tag: 
  adm: 
  vis: 
  tp: 
  chat: 
  spec: 
  autosoup: 
  fps: 
  hack: 
  troll: 
  fake:
  fftest:
  tfake: 
  1v1:
  specs: 
  loja: 
  sc: 
  setwarp:
  delwarp:
  build: 
  fakes:                       
  warp:
  resetkdr:
  togglesc:
  macrotest:
  youtuber:      
  head:               
  aplicacao:                     
  broadcast:                         
  bc:                         
  evento: 
  anunciovip: 
  anunciounban: 
  anunciodoacao: 
  anunciokit: 
  duvida:                                                                                 
  rd: 
  invis: 
  r: 
  warps: 
  sopa: 
  heal: 
  ajuda: 
  fly: 
  spawn: 
  kit: 
  epvp:
  resetkit: 
  addmoney: 
  removemoney: 
  setmoney: 
  money: 
  report:                                    
  setrank: 
  mlg:
  clear: 
  ac:
  admin:
  tell:
  cc: 
  dano:
  gm:
  unmute:
  v:
  lc:
  skit:
  tpall:
  inv:
  invsee:
  kick:
  ban:
  unban:
  espada:
  mute: