name: WoCHG
author: EvertonPvP
main: me.everton.hg.Main
version: 1.0
commands:
  aplicacao:
  autosoup:
  antikb:
  fake:
  tfake:
  fakes:
  sc:
  ac:
  spawn:
  start:
  admin:
  adm:
  specs:
  info:
  help:
  jogo:
  tempo:
  arena:
  togglekits:
  tag:
  report:
  tp:
  tpall:
  skit:
  invis:
  kit:
  kits:
  cc:
  ffeast:
  tpfeast:
  feast: