name: WoCPvP
author: EvertonPvP
main: me.everton.WocPvP.Main
version: 1.0
description: Plugin de KitPvP criado por EvertonPvP
depend: [WorldGuard,WorldEdit,TagAPI,BarAPI]
commands: 
  tag: 
  adm: 
  vis: 
  tp: 
  chat: 
  spec: 
  autosoup: 
  fps: 
  hack: 
  troll: 
  fake: 
  tfake: 
  specs: 
  loja: 
  sc: 
  construir: 
  fakes:                       
  youtuber:                     
  aplicacao:                     
  broadcast:                         
  bc:                         
  evento: 
  anunciovip: 
  anunciounban: 
  anunciodoacao: 
  anunciokit: 
  duvida:                                                                                 
  rd: 
  invis: 
  r: 
  warps: 
  sopa: 
  heal: 
  ajuda: 
  fly: 
  spawn: 
  kit: 
  wocpvp:
  resetkit: 
  addmoney: 
  removemoney: 
  setmoney: 
  money: 
  report:                                    
  setrank: 
  grappler: 
  switcher:
  endermage:
  stomper:
  pvp:
  infernor:
  gladiator:
  mlg:
  clear:
  kangaroo:
  hulk:        